apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: baas
  name: baas
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: baas:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: dev
      uri: https://github.com/appuio/baas.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: centos:7
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: bla
    type: GitHub
  - type: ConfigChange
  - type: ImageChange
