apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: baas
    name: baas
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: baas
    name: centos
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos:7
      from:
        kind: DockerImage
        name: centos:7
      generation: 2
      importPolicy: {}
      name: "7"
      referencePolicy:
        type: Source
